version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: baseone-chatbot-postgres
    environment:
      POSTGRES_USER: baseone
      POSTGRES_PASSWORD: baseone
      POSTGRES_DB: baseone
    ports:
      - "10003:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U baseone -d baseone"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: baseone-chatbot-redis
    ports:
      - "10004:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: